ooyala/html5-common

.gitignore
Makefile
js/classes/message_bus.js
package.json
test/unit-test-helpers/default_test_env.js
test/unit-test-helpers/message_bus_helper.js
test/unit-tests/emitter_test.js
test/unit-tests/message_bus_test.js
test/unit-tests/state_machine_test.js
test/unit-tests/utils_test.js

This is pulling in the latest version of all the files from our core repo and getting unit tests to work.  The next step will be to rip out these files from the other repo.

Unit tests

---

js/utils/constants.js
js/utils/environment.js

Change feature "open" to "give" and "take" and move requiresSingleVideoElement to common utils

[PBW-3665] VTC: Support iOS (single element mode) for IMA

---

js/utils/constants.js

Associated with:
https://github.com/ooyala/html5-video-plugins/pull/96
https://github.com/ooyala/html5-ad-plugins/pull/48
And two internal pull requests

[PBW-2677] Add event to prime video elements for devices

---

js/utils/constants.js

Removes unused akamai encoding definitions

[PBF-534] Add akamai HD3 encoding

---

js/utils/environment.js

This is step one for the bug fixes needed for PBW-4555

[PBW-4555] Update enviroment for Edge browser

---

js/utils/constants.js

This reverts commit 985c138763676519c533e27b8601ccd9152cd949.

Revert "[PBF-534] Add akamai HD3 encoding"

---

js/utils/constants.js

@angieisrani Please review it.

add two encodings for drm support

---

js/utils/constants.js

@angieisrani Please review it.

[AT-2818] Change stream definition of VC_CREATE_VIDEO_ELEMENT

---

js/utils/constants.js

Adds encoding for Akamai live/remote for secure tokens.
See pull requests in:
mjolnir
html5-common
html5-video-plugins

[PBF-661] Adds encoding for Akamai live/remote for secure tokens.

---

js/utils/constants.js

-created a video encoding type PULSE for the Pulse plugin to use

[PSDK-542]

---

js/utils/constants.js

⚠️  merge with - https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/157/overview

[PLAYER-43] Constant added for playlistReady

---

js/utils/constants.js

this event will be published by core and subscribed to by skin

[PLAYER-20] adding new event: SKIN_METADATA_FETCHED

---

js/utils/constants.js

See also: https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/197/overview

[PBF-818] Prevent Ad UI on subsequent playlist videos in mobile.

---

js/utils/environment.js

-added an environment util function to check if browser supports MSE

[support-mse-util]

---

js/utils/constants.js

-updated constants to include SDK_AD_EVENT

[player-1256]

---

js/utils/constants.js

-added description_url to OO.TEMPLATES.REFERAK_PLACE_HOLDER so that the description_url macro can be replaced with the page url

[player-1376]

---

js/utils/constants.js

PR to add some constants for QoS events

Player 1532

---

js/utils/constants.js

-added new mute and unmute message bus events
-sync up INITIAL_PLAY jsdoc with mjolnir

Player 1897

---

js/utils/constants.js

-syncing up with new muted autoplay messages

[player-1788]

---

js/utils/utils.js

This is needed for the changes for PLAYER-2672. Eventually we should replace the references from Utils in the skin with this function.
The unit tests are on the Mjolnir PR, since this project's unit tests are broken.
This needs to be merged together with the following PR's:
https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/422/overview
https://github.com/ooyala/html5-skin/pull/1007

[PLAYER-2672] Added OO.ensureNumber function

---

js/utils/constants.js

-added tracking level to constants

[player-3515]

---

js/utils/environment.js

-fixed an issue where the isAndroid4_4Plus function was returning true in all non-Android environments

[player-3876]

---

package-lock.json
package.json

-updated dependencies to work with Node version 8.11.3

[player-3986] - Update to Node 8.11.3

---

js/utils/constants.js

https://jira.corp.ooyala.com/browse/PLAYER-4679
Changed SEEK_TO_END_LIMIT to 3 seconds so the testing asset ( 3.1s duration) can be replayed
Anton Zelenskii update: this is not a fix in good term, but a patch. The strategy of seek to end sticking must be discussed with PO

Changed SEEK_TO_END_LIMIT

---

package.json

Added package.json commands (dummy for now) to unblock devops

chore/PLAYER-4987 Added package.json commands (dummy for now) to unblock devops

---

.editorconfig
package.json
test/unit-test-helpers/default_test_env.js
test/unit-tests/emitter_test.js
test/unit-tests/message_bus_test.js

Changed arguments to ...args, because the library cannot compare the data of a non-real array of type argument with the data of the object type

[PLAYER-5361] fix tests

---

js/utils/constants.js

corresponding pr in mjolnir: https://git.corp.ooyala.com/projects/PBW/repos/mjolnir/pull-requests/668/overview

[PLAYER-5400] remove VC_PRIME_VIDEOS event
